---
title: >-
  Hashi @
  Home
email: brucellino@hey.com
description: >-
  Sharp tools, sharp mind. The story of using Hashicorp tools in a home-made setup
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hashiatho.me" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 1
paginate_path: "posts/:num"
paginate_tag_basepath: '/tag/:name'

twitter_username: brusisceddu
github_username:  brucellino
highlighter: rouge
# Build settings
markdown: kramdown
repository: brucellino/hashiatho.me
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  toc_levels: 1..4
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
theme_color: solarized
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
plugins:
  - jekyll-paginate
