---
title: >-
  Hashi @
  Home
email: brucellino@hey.com
description: >-
  Sharp tools, sharp mind. The story of using Hashicorp tools in a home-made setup
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hashiatho.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: brusisceddu
github_username:  brucellino

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
theme_color: solarized
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
